quarkus.http.port=4315
quarkus.package.jar.type=uber-jar
quarkus.package.jar.add-runner-suffix=false
quarkus.package.jar.user-configured-ignored-entries=ai/onnxruntime/native/win-x64/onnxruntime.pdb
quarkus.banner.path=banner.txt

quarkus.log.console.enable = true
quarkus.log.file.enable = false
quarkus.log.category."dev.langchain4j.mcp".level=WARN